version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
  backend:
    build: .
    ports:
      - 8000:8000
    environment:
      ROCKET_MONGODB_URL: mongodb://root:root_password@mongo/
      ROCKET_PORT: 8000
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_LOG_LEVEL: normal
      # you public key
      ROCKET_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxVjs/OfpWZCPMWz/OrSJ
        Kca89ZFmXyOStmf4rIPfKztiTmvZQhq8dPHtiTdjBDVwIur78BvEj3sF98Ot/Ssq
        Ywmf+G3xKp2dPx8ULtejNQvOX3Mh+h/wV3lkGL9KNrFqAcGHi81g8BMhkNMfxIJ+
        2Hq/RkgbnWe/Y1vB67U2HLAmk/spjlU/u+zr/BpK7+0BvPCdSRzSwctD3e1L5zOf
        xHg225RtG8wcqGp3TtaCpN2ya8hcSLmG7BPfZiZSPKF3yceXF2PnC/WjMEasfvHB
        OWFcYZzngKx/5ZqaXYwPbL6dtx91G1Z8hi/ISMAc5pHfNZobfTJ5NwiLBHpYV9iy
        XQIDAQAB
        -----END PUBLIC KEY-----
      # you private key
      ROCKET_PRIVATE_KEY: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAxVjs/OfpWZCPMWz/OrSJKca89ZFmXyOStmf4rIPfKztiTmvZ
        Qhq8dPHtiTdjBDVwIur78BvEj3sF98Ot/SsqYwmf+G3xKp2dPx8ULtejNQvOX3Mh
        +h/wV3lkGL9KNrFqAcGHi81g8BMhkNMfxIJ+2Hq/RkgbnWe/Y1vB67U2HLAmk/sp
        jlU/u+zr/BpK7+0BvPCdSRzSwctD3e1L5zOfxHg225RtG8wcqGp3TtaCpN2ya8hc
        SLmG7BPfZiZSPKF3yceXF2PnC/WjMEasfvHBOWFcYZzngKx/5ZqaXYwPbL6dtx91
        G1Z8hi/ISMAc5pHfNZobfTJ5NwiLBHpYV9iyXQIDAQABAoIBADlyAkI4K7fzmYsU
        pFLtXIP5ouWEtpz5GOrZ5wwosty9w4b6Y9qXN8Z+6dsocT03ZPX1GvMw0g3GDN2r
        a0knuIXttlA1iJ8UFELchB6CjLKTRjaIqBpME8USw+1kOXEkQaxTLmammRIpL3sd
        ycCFD/FqAaWutcMjARYmDpPTQvYkWYyRNFhsuCC9P9ZooHkyrgG85pxQDJhzMY8E
        ERIlrhYMhAfLzbpLWJCIGW6JJtOK3uxXzjKPmfSeIT2GuJcGKMJopt+xnBfJU49w
        0X8Oz69+QBr/NT0f0ZvT8NXTeY8PjCkf6wZkFncsIZaf27BVupZD7L5sAUhzQsi5
        Phew6Y0CgYEA6pVF62ZqJ0SkDQzMdok2qYsIqBCmexBdlTw9ssZkpsuENBRm+oEo
        tikQoOsHmhb78fBY8xle+2El6R+JwVqiIX8T5Up0G7u1QZF/CzwM8rY8S/Tfym0r
        H/zlNPTvzp5GYUJzyuK6n44apaIrnKYSiyfW5I5J39pUWcANK5QSHUsCgYEA111e
        /BWSwyc/M4H/Yc2Ah8Ywyw3jLJ+0UjykxIKH+zeWHWyxg244KywhAdiyKM9YYrto
        nQuwGYCmMo9YPymle/4PDKGSi9yZLBSRwJVnqWdhkFIfwXVKgbeL2sAIbzQJ93+U
        U6YpmYiZtTTHRoGP3KmNw/BH3dyOQMDdABfA7fcCgYBkqO0519aRRxkGKInMC5ET
        K3/pbkuh3yHpGdJ31j32fLocBu0xbR7lG7Xw9ylp65bs+G+S0T46rDMyV8Aq4hNU
        QE1vRIWSKPfcTOyxC3Ga7KvvBALLwBCTR1erY7dLeAtHTNaXJrdiI/43OOFx9Klc
        YRoLNStqDSvI32pHWuBzBQKBgHiAAM5xT62rvvwV54uUjS7q4JAslAh6z00YK2Tc
        WDNitbZ/A4+zUvAs/8bltUGKSjzr+Sutx3ltdxBhDhJBPhtzWn5JxRJGetmkJK0p
        q1eoxXkXyjbXZrnPtgvOWKnH5y+5DYgEN9B1EvPFtR4pDhJ8OBsCzWNArcNjZgRQ
        Rh2fAoGACE4fBiVrsey1vwH+s7Yy9IVQyu8JIfFWNWRsrftAU2ZBnJNXdpuLrtU8
        JYML5AtPVgX2160tt2NRqWr81u1IlMt9MGG8XnzVKMaUtbfBdn11SZoufVMuhLIu
        of0n2pq5ef+j6b8waGHYBj1feqWodi5RY4d/BKDbO3aWpiOqizE=
        -----END RSA PRIVATE KEY-----
      # you google OAuth app id
      ROCKET_GOOGLE_OAUTH_ID: ""
      # you google OAuth app secret
      ROCKET_GOOGLE_OAUTH_SECRET: ""
      ROCKET_GOOGLE_ACCOUNT_EMAIL: ""
      ROCKET_GOOGLE_ACCOUNT_PASSWORD: ""

      # you facebook Login app id
      ROCKET_FACEBOOK_OAUTH_ID: ""
      # you facebook Login app secret
      ROCKET_FACEBOOK_OAUTH_SECRET: ""

      ROCKET_ISSUER: "http://127.0.0.1:8000"
    depends_on:
      - mongo
