name: Deploy
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Generator docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          toolchain: stable
          args: --no-deps -p router --document-private-items
      - name: Create index.html
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=router\">" > target/doc/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          cname: api-docs.lipoic.org
