name: Pull request review
on: [pull_request]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true          
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ github.token }}
          toolchain: nightly
          args: --all-features
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: stable
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Generator docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          toolchain: stable
          args: --no-deps -p router --document-private-items
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=router\">" > target/doc/index.html
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
